var glob = require("glob");
const fs = require("fs");

const capitalize = (string) => {
  return string ? string.charAt(0).toUpperCase() + string.slice(1) : "";
}

function writeLines(surveyName) {
  const uppercaseName = capitalize(surveyName)
  return `
import ${surveyName}Json from "../surveys/${surveyName}/${surveyName}.json";
import { default as ${surveyName}ScoreFunc } from "../surveys/${surveyName}/${surveyName}.score.js";
export const ${uppercaseName} = SurveyFactory("${surveyName}", ${surveyName}Json, ${surveyName}ScoreFunc);
`;
}



glob("surveys/*/", function (er, dirs) {
  surveyNames = dirs.map((dir) => dir.split("/")[1]);

  var lines = [`// auto-generated by builder.js
// run "npm run build" to regenerate
// automatically rebuilt on push

import SurveyFactory from "./surveyFactory.jsx"
`];

  lines.push(...surveyNames.map(writeLines));
  const content = lines.join("");
  console.log("building index.js")

  fs.writeFile("src/index.js", content, (err) => {
    if (err) {
      console.error(err);
    }
  });
});
