// auto-generated by builder.js
// run "npm run build" to regenerate
// automatically rebuilt on push

import SurveyFactory from "./surveyFactory.jsx"

import attitudeAttributesJson from "../surveys/attitudeAttributes/attitudeAttributes.json";
import attitudeAttributesSha from "../surveys/attitudeAttributes/sha.json";
import { default as attitudeAttributesScoreFunc } from "../surveys/attitudeAttributes/attitudeAttributes.score.js";
export const AttitudeAttributes = SurveyFactory("attitudeAttributes", attitudeAttributesJson, attitudeAttributesScoreFunc, attitudeAttributesSha);

import autonomyNeedSatisfactionJson from "../surveys/autonomyNeedSatisfaction/autonomyNeedSatisfaction.json";
import autonomyNeedSatisfactionSha from "../surveys/autonomyNeedSatisfaction/sha.json";
import { default as autonomyNeedSatisfactionScoreFunc } from "../surveys/autonomyNeedSatisfaction/autonomyNeedSatisfaction.score.js";
export const AutonomyNeedSatisfaction = SurveyFactory("autonomyNeedSatisfaction", autonomyNeedSatisfactionJson, autonomyNeedSatisfactionScoreFunc, autonomyNeedSatisfactionSha);

import awarenessMonitoringGrowthJson from "../surveys/awarenessMonitoringGrowth/awarenessMonitoringGrowth.json";
import awarenessMonitoringGrowthSha from "../surveys/awarenessMonitoringGrowth/sha.json";
import { default as awarenessMonitoringGrowthScoreFunc } from "../surveys/awarenessMonitoringGrowth/awarenessMonitoringGrowth.score.js";
export const AwarenessMonitoringGrowth = SurveyFactory("awarenessMonitoringGrowth", awarenessMonitoringGrowthJson, awarenessMonitoringGrowthScoreFunc, awarenessMonitoringGrowthSha);

import conflictAndViabilityJson from "../surveys/conflictAndViability/conflictAndViability.json";
import conflictAndViabilitySha from "../surveys/conflictAndViability/sha.json";
import { default as conflictAndViabilityScoreFunc } from "../surveys/conflictAndViability/conflictAndViability.score.js";
export const ConflictAndViability = SurveyFactory("conflictAndViability", conflictAndViabilityJson, conflictAndViabilityScoreFunc, conflictAndViabilitySha);

import constructiveListeningBehaviorsJson from "../surveys/constructiveListeningBehaviors/constructiveListeningBehaviors.json";
import constructiveListeningBehaviorsSha from "../surveys/constructiveListeningBehaviors/sha.json";
import { default as constructiveListeningBehaviorsScoreFunc } from "../surveys/constructiveListeningBehaviors/constructiveListeningBehaviors.score.js";
export const ConstructiveListeningBehaviors = SurveyFactory("constructiveListeningBehaviors", constructiveListeningBehaviorsJson, constructiveListeningBehaviorsScoreFunc, constructiveListeningBehaviorsSha);

import constructiveListeningBehaviorsSelfJson from "../surveys/constructiveListeningBehaviorsSelf/constructiveListeningBehaviorsSelf.json";
import constructiveListeningBehaviorsSelfSha from "../surveys/constructiveListeningBehaviorsSelf/sha.json";
import { default as constructiveListeningBehaviorsSelfScoreFunc } from "../surveys/constructiveListeningBehaviorsSelf/constructiveListeningBehaviorsSelf.score.js";
export const ConstructiveListeningBehaviorsSelf = SurveyFactory("constructiveListeningBehaviorsSelf", constructiveListeningBehaviorsSelfJson, constructiveListeningBehaviorsSelfScoreFunc, constructiveListeningBehaviorsSelfSha);

import demographicsJson from "../surveys/demographics/demographics.json";
import demographicsSha from "../surveys/demographics/sha.json";
import { default as demographicsScoreFunc } from "../surveys/demographics/demographics.score.js";
export const Demographics = SurveyFactory("demographics", demographicsJson, demographicsScoreFunc, demographicsSha);

import discussionQualityControlJson from "../surveys/discussionQualityControl/discussionQualityControl.json";
import discussionQualityControlSha from "../surveys/discussionQualityControl/sha.json";
import { default as discussionQualityControlScoreFunc } from "../surveys/discussionQualityControl/discussionQualityControl.score.js";
export const DiscussionQualityControl = SurveyFactory("discussionQualityControl", discussionQualityControlJson, discussionQualityControlScoreFunc, discussionQualityControlSha);

import discussionSelfInsightJson from "../surveys/discussionSelfInsight/discussionSelfInsight.json";
import discussionSelfInsightSha from "../surveys/discussionSelfInsight/sha.json";
import { default as discussionSelfInsightScoreFunc } from "../surveys/discussionSelfInsight/discussionSelfInsight.score.js";
export const DiscussionSelfInsight = SurveyFactory("discussionSelfInsight", discussionSelfInsightJson, discussionSelfInsightScoreFunc, discussionSelfInsightSha);

import exampleSurveyJson from "../surveys/exampleSurvey/exampleSurvey.json";
import exampleSurveySha from "../surveys/exampleSurvey/sha.json";
import { default as exampleSurveyScoreFunc } from "../surveys/exampleSurvey/exampleSurvey.score.js";
export const ExampleSurvey = SurveyFactory("exampleSurvey", exampleSurveyJson, exampleSurveyScoreFunc, exampleSurveySha);

import lonelinessSingleItemJson from "../surveys/lonelinessSingleItem/lonelinessSingleItem.json";
import lonelinessSingleItemSha from "../surveys/lonelinessSingleItem/sha.json";
import { default as lonelinessSingleItemScoreFunc } from "../surveys/lonelinessSingleItem/lonelinessSingleItem.score.js";
export const LonelinessSingleItem = SurveyFactory("lonelinessSingleItem", lonelinessSingleItemJson, lonelinessSingleItemScoreFunc, lonelinessSingleItemSha);

import partisanFeelingThermometerUSJson from "../surveys/partisanFeelingThermometerUS/partisanFeelingThermometerUS.json";
import partisanFeelingThermometerUSSha from "../surveys/partisanFeelingThermometerUS/sha.json";
import { default as partisanFeelingThermometerUSScoreFunc } from "../surveys/partisanFeelingThermometerUS/partisanFeelingThermometerUS.score.js";
export const PartisanFeelingThermometerUS = SurveyFactory("partisanFeelingThermometerUS", partisanFeelingThermometerUSJson, partisanFeelingThermometerUSScoreFunc, partisanFeelingThermometerUSSha);

import perceptionOfOthersJson from "../surveys/perceptionOfOthers/perceptionOfOthers.json";
import perceptionOfOthersSha from "../surveys/perceptionOfOthers/sha.json";
import { default as perceptionOfOthersScoreFunc } from "../surveys/perceptionOfOthers/perceptionOfOthers.score.js";
export const PerceptionOfOthers = SurveyFactory("perceptionOfOthers", perceptionOfOthersJson, perceptionOfOthersScoreFunc, perceptionOfOthersSha);

import persuasionAndLearningJson from "../surveys/persuasionAndLearning/persuasionAndLearning.json";
import persuasionAndLearningSha from "../surveys/persuasionAndLearning/sha.json";
import { default as persuasionAndLearningScoreFunc } from "../surveys/persuasionAndLearning/persuasionAndLearning.score.js";
export const PersuasionAndLearning = SurveyFactory("persuasionAndLearning", persuasionAndLearningJson, persuasionAndLearningScoreFunc, persuasionAndLearningSha);

import politicalPartyUSJson from "../surveys/politicalPartyUS/politicalPartyUS.json";
import politicalPartyUSSha from "../surveys/politicalPartyUS/sha.json";
import { default as politicalPartyUSScoreFunc } from "../surveys/politicalPartyUS/politicalPartyUS.score.js";
export const PoliticalPartyUS = SurveyFactory("politicalPartyUS", politicalPartyUSJson, politicalPartyUSScoreFunc, politicalPartyUSSha);

import psychologicalSafetyJson from "../surveys/psychologicalSafety/psychologicalSafety.json";
import psychologicalSafetySha from "../surveys/psychologicalSafety/sha.json";
import { default as psychologicalSafetyScoreFunc } from "../surveys/psychologicalSafety/psychologicalSafety.score.js";
export const PsychologicalSafety = SurveyFactory("psychologicalSafety", psychologicalSafetyJson, psychologicalSafetyScoreFunc, psychologicalSafetySha);

import relatednessNeedSatisfactionJson from "../surveys/relatednessNeedSatisfaction/relatednessNeedSatisfaction.json";
import relatednessNeedSatisfactionSha from "../surveys/relatednessNeedSatisfaction/sha.json";
import { default as relatednessNeedSatisfactionScoreFunc } from "../surveys/relatednessNeedSatisfaction/relatednessNeedSatisfaction.score.js";
export const RelatednessNeedSatisfaction = SurveyFactory("relatednessNeedSatisfaction", relatednessNeedSatisfactionJson, relatednessNeedSatisfactionScoreFunc, relatednessNeedSatisfactionSha);

import rmetTenJson from "../surveys/rmetTen/rmetTen.json";
import rmetTenSha from "../surveys/rmetTen/sha.json";
import { default as rmetTenScoreFunc } from "../surveys/rmetTen/rmetTen.score.js";
export const RmetTen = SurveyFactory("rmetTen", rmetTenJson, rmetTenScoreFunc, rmetTenSha);

import SVIJson from "../surveys/SVI/SVI.json";
import SVISha from "../surveys/SVI/sha.json";
import { default as SVIScoreFunc } from "../surveys/SVI/SVI.score.js";
export const SVI = SurveyFactory("SVI", SVIJson, SVIScoreFunc, SVISha);

import teamViabilityJson from "../surveys/teamViability/teamViability.json";
import teamViabilitySha from "../surveys/teamViability/sha.json";
import { default as teamViabilityScoreFunc } from "../surveys/teamViability/teamViability.score.js";
export const TeamViability = SurveyFactory("teamViability", teamViabilityJson, teamViabilityScoreFunc, teamViabilitySha);

import TIPIJson from "../surveys/TIPI/TIPI.json";
import TIPISha from "../surveys/TIPI/sha.json";
import { default as TIPIScoreFunc } from "../surveys/TIPI/TIPI.score.js";
export const TIPI = SurveyFactory("TIPI", TIPIJson, TIPIScoreFunc, TIPISha);
