name: Cypress Component Tests

on:
  [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cypress run  
      uses: cypress-io/github-action@v4.2.0
      with:
        install: false
        component: true
       env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}