name: Cypress Component Tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  cypress_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        browser: [chrome, firefox, edge]

    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: ${{ matrix.browser }}
          build: npm run build
          component: true
          record: true
          group: "${{ matrix.browser }} on ${{ matrix.os }}"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
